kylemichaelreaves/rails-pg-app

db/migrate/20211120220310_remove_column.rb
db/migrate/20211120225108_adding_column_to_property.rb
db/migrate/20211120225700_remove_column_from_property.rb
db/migrate/20211120230420_remove_associated_properties_from_landlord.rb
db/migrate/20211120230918_renaming_column_in_landlords.rb
db/schema.rb

list_properties_owned clearly identifies column type: an array of strings

Changing properties and landlords tables with migrations

---

db/migrate/20211122000307_remove_column_from_properties.rb
db/schema.rb

though it had a different name, it was essentially the same column.

Removed a duplicated column;

---

db/migrate/20211122012027_remove_owner_full_mailding_address_from_landlords.rb
db/schema.rb

The column masquerading under a different name.

Removed another duplicate column 

---

db/migrate/20211122034139_remove_number_of_properties_owned_from_properties.rb

No longer trying to delete a column that isn't there.

Migrations are unblocked now.

---

.gitignore
app/assets/stylesheets/landlords.scss
app/controllers/landlords_controller.rb
app/controllers/pages_controller.rb
app/controllers/properties_controller.rb
app/controllers/property_controller.rb
app/helpers/landlords_helper.rb
app/models/landlord.rb
app/views/landlords/index.html.erb
config/routes.rb
package-lock.json
test/controllers/landlords_controller_test.rb
yarn.lock

- Package updates for the React side of things.
- Generated controllers for `properties` and `landlords`.
- Adding routes for the controllers. Each controller contains an `index` and `show` function.

Package updates, controllers, and routes

---

Gemfile.lock
app/models/landlord.rb
app/models/property.rb
db/migrate/20211125183047_add_association_to_property.rb
db/migrate/20211125185105_add_association_to_landlord.rb
yarn.lock

Property and Landlord models updated. 
Problematic syntax removed. 
Gems updated, TypeScript updated.

Models and Gems updated

---

Gemfile.lock
README.md
yarn.lock

Readme updated with `.node-version` and `.ruby-version`;
Specifying these were necessary in order to get the repo running
locally. They already existed in origin.

Readme updated

---

README.md
yarn.lock

While it's not feasible to track large databases, this database is relatively small.
I "dumped" the database with `pg_dump` and moved the .sql file to this repo.
How I loaded the data into the Property model (with a Rakefile task) is now in the Readme.

Package updates, database and Readme

---

app/views/properties/index.html.erb
yarn.lock

It iterates over each item in the Postgres database.

View added for Property model.

---

yarn.lock

Front and backend packages/gems updated.

Yarn and Gem updates

---

app/controllers/properties_controller.rb
app/javascript/routes/Index.jsx
yarn.lock

A few methods added to the Properties controller…the `create` method needs validation from the `geocoder` gem.
A route for the React front-end I got from 
[a tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-ruby-on-rails-project-with-a-react-frontend)
Yarn package updates.

Controllers, routes, and packages

---

app/javascript/components/Home.tsx
yarn.lock

d3 updated to its latest version.
the Home function component, though still a skeleton, is updated with
the correct TypeScript syntax.

Updated d3, TS syntax for Home component

---

.gitignore
.solargraph.yml
yarn.lock

generated solargraph.yml with the command `solargraph config`

Updated eslint, added solargraph for Ruby

---

.gitignore
app/views/properties/index.html.erb

I took out `.solargraph.yml` from the gitignore since it didn't seem to ignore it anyway.
Added a list item for `property.id` to the Property list.

Added Property value to its views

---

Gemfile
Gemfile.lock
README.md
app/helpers/properties_helper.rb
app/models/property.rb
app/views/properties/index.html.erb
db/migrate/20220117193532_add_foreign_keys_to_landlord.rb
db/seeds.rb
yarn.lock

Instead of using a Rakefile task to seed the data, I've begun migrating to seeds.rb in the db folder.
I added a few queries for ActiveRecord to the README.
The Properties list in properties/index.html.erb is now a table.
Properties model updated with a few validations.
Geocoder gem added.
A migration that added a foreign key to Landlord was deleted.

Package updates, seeds, validations

---

README.md

I took out the sections that are better left to the Rails documentation.

Tidied up the Readme.

---

.prettierrc
Gemfile.lock
db/migrate/20220130195957_add_name_to_landlord.rb
db/schema.rb
db/seeds.rb
yarn.lock

…with data from the Property model. More specifically: `Landlord.pluck(:owner_name).uniq`
Added the appropriate column name ('name') for the Landlord model.
Yarn and gem package updates.

Seeded Landlord

---

db/migrate/20220206000750_adding_landlord_idto_property_table.rb
db/schema.rb

Association between Landlord and Property added.

Added Association

---

README.md
app/models/landlord.rb
app/models/property.rb
db/migrate/20220206000750_adding_landlord_idto_property_table.rb
db/migrate/20220206021643_add_foreign_key_to_property.rb
db/migrate/20220206022820_remove_foreign_key_from_property.rb
db/migrate/20220206023315_remove_landlords_id_from_properties.rb
db/migrate/20220206035551_add_column_to_landlord.rb
db/migrate/20220206043208_change_column_type_on_landlord.rb
db/migrate/20220206043652_add_column_to_landlords.rb
db/migrate/20220206043907_add_columns_to_landlords.rb
db/schema.rb
db/seeds.rb

Seeded by calling Property model within an each-do block, iterating over unique_landlord_names array. 
Repeated the same pattern for each of the columns I needed.
Next up: addin landlord_id as a foreign key into the properties table.

Actually seeded Landlord with data

---

app/models/landlord.rb

Removing confusing foreign-key

---

Gemfile.lock
app/controllers/properties_controller.rb
app/helpers/.prettierrc
app/helpers/properties_helper.rb
app/javascript/components/App.tsx
app/javascript/components/Home.tsx
app/javascript/packs/Index.jsx
app/javascript/routes/Index.jsx
app/models/landlord.rb
app/views/properties/index.html.erb
package.json
test/controllers/pages_controller_test.rb
test/controllers/properties_controller_test.rb
test/models/property_test.rb
yarn.lock

It may take a few seconds — there are 60k properties, aren't there? 
And we are currently loading them all at once it seems. 
Another strategy would be pagination.
Package updates. And a few packages added, like Formik. 
Code commented out in places where it's incomplete. I'll come back to it.

Properties table sorts by id

---

app/javascript/components/PropertyLoader.tsx

…but does it get from the local host?

PropertyLoader added

---

app/assets/stylesheets/application.css
app/javascript/Index.jsx
app/javascript/components/Home.tsx
app/javascript/components/PropertyTable.tsx
app/javascript/routes/Index.tsx
app/views/layouts/application.html.erb
config/webpack/webpack.config.js

I think I need to add this to get bootstrap going…so say [their](https://getbootstrap.com/docs/4.0/getting-started/webpack/#importing-styles) docs at least.

webpack.config modified

---

app/controllers/api/v1/landlords_controller.rb
app/controllers/api/v1/properties_controller.rb
app/models/landlord.rb
config/routes.rb
db/schema.rb
yarn.lock

The API now returns `Property` and `Landlord` records as JSON objects, which will soon be rendered within their respective functional components.

API Calls working

---

app/controllers/application_controller.rb
app/javascript/components/App.tsx
app/javascript/components/Home.tsx
app/javascript/components/NavBar.tsx
app/javascript/components/Property/Properties.tsx
app/javascript/components/Property/Property.tsx
app/javascript/components/Property/getPropertyById.tsx
app/javascript/components/Property/useProperties.tsx
app/javascript/components/Property/useProperty.tsx
config/routes.rb
tsconfig.json
yarn.lock

Since I'm using TypeScript, there was some minor finessing that I had to do, specifying the return types for the useQuery hook. It was necessary to use undefined in some instances, and in one spot to use an optional chain operator.
[This](https://tkdodo.eu/blog/react-query-and-type-script) guide on resolving the TypeScript linter problems was indispensable.

Rails API now rendering inside React

---

Gemfile
Gemfile.lock
app/helpers/properties_helper.rb
app/javascript/components/GeocoderForm.tsx
app/javascript/components/Home.tsx
app/jobs/import_data_job.rb
bin/delayed_job
config/application.rb
db/migrate/20220303221842_create_delayed_jobs.rb
db/schema.rb
lib/tasks/import_data.rake
test/jobs/import_data_job_test.rb

I didn't finish the delayed job for the CSV import. [Apparently](https://pganalyze.com/blog/fastest-way-importing-data-into-postgres-with-ruby-rails) delayed_jobs are a particularly performant way of executing tasks like a bulk csv import.
Made a GeocoderForm component. It doesn't yet point toward to the Rails API. I am thinking that a ref might be an appropriate way to concatenate those fields into the field that will be geocoded by Rails.

CSV import task started; GeocoderForm component

---

app/javascript/components/Address/CreateAddress.tsx
app/javascript/components/GeocoderForm.tsx

Following [this example](https://react-query.tanstack.com/examples/optimistic-updates-typescript) to implement a `useMutation` hook, which also makes use of axios's `post` action.

useMutation hook for CRUD actions

---

app/controllers/concerns/pagination.rb
app/javascript/components/App.tsx
app/javascript/components/Home.tsx
app/javascript/components/Property/Properties.tsx
app/javascript/components/Property/Property.tsx
app/javascript/components/Property/useProperties.tsx
app/javascript/components/hooks/useEventListener.tsx
app/javascript/components/hooks/useIntersectionObserver.tsx
package.json
yarn.lock

[useEventListener](https://usehooks-ts.com/react-hook/use-event-listener) hook added…since essentially the infinite scroll function listens for when the user reaches the bottom. There are a few ways to do this. I still haven't figured out the corresponding changes in the properties_controller.
Cleaned up the `Properties` component; removed unused imports.

useInfiniteQuery + eventListeners

---

Gemfile.lock
app/javascript/components/Property/Properties.tsx
app/javascript/components/Property/useProperties.tsx
yarn.lock

in Properties. I did not properly loop over the data object. This has been changed to fit the [Infinite Scroll](https://react-query.tanstack.com/examples/load-more-infinite-scroll) example in the react-query documentation.

Fixes to data loop

---

app/javascript/components/Home.tsx
app/javascript/components/searchBar.tsx

searchBar removed for the time being…
Geocoder removed from Home.

Separating components

---

app/models/landlord.rb

Suddenly it occured to me to have model methods.

Landlord methods added

---

Gemfile.lock
app/javascript/components/Property/Properties.tsx
app/models/address.rb
app/models/landlord.rb
db/migrate/20220406012602_rename_column_property_location_in_address_to_street_address.rb
db/schema.rb
node_modules/@types/react-table/index.d.ts
yarn.lock

Minor changes to the Properties.tsx component.
Migration generated to rename a column in Addresses, to be consistent with other models.

Address model updated

---

Gemfile.lock
app/javascript/Index.jsx
app/jobs/import_csv_job.rb
app/models/address.rb
db/migrate/20220407021133_adding_longitude_and_latitude_to_addresses.rb
db/schema.rb
yarn.lock

In order for this to work, I added `latitude` and `longitude` to the `Address` model.

Address now validates with geocode

---

app/javascript/components/Property/Properties.tsx
app/javascript/components/Property/getPropertyById.tsx
app/javascript/components/Property/usePropertiesCount.tsx
package.json
yarn.lock

from `Properties.tsx`.
Removed unused import from `getPropertyById.tsx`.

Separated the usePropertiesCount function

---

app/javascript/components/Property/Properties.tsx
app/javascript/components/searchBar.tsx

Building SearchBar component

---

Gemfile
Gemfile.lock
app/javascript/components/Property/Properties.tsx
app/javascript/components/searchBar.tsx
app/models/property.rb
config/application.rb
test/controllers/properties_controller_test.rb
test/fixtures/addresses.yml
test/fixtures/landlords.yml
test/models/landlord_test.rb
test/system/addresses_test.rb
test/system/properties_test.rb
yarn.lock

`SearchBar` component was preventing the `Properties` component from updating; that has been resolved. 
Event types specified inside the react-bootstrap component (`SearchBar`).
`config/application.rb`: 
– explicitly telling Rails to function as an API, since this is what I'm doing already.
Tried getting tests to work…toward that end I generated a few Address fixtures. Or, the fixtures were generated when I generated the Address model. But I originally generated `zipcode` as an integer but quickly realized it needed to be a string in order for the geocoding to work.
I am not sure if the tests are failing because I started this app as a whole Rails app but then transitioned to only using it as an API.

Component, model, and test updates

---

Gemfile
Gemfile.lock
README.md
app/controllers/api/v1/addresses_controller.rb
app/controllers/api/v1/landlords_controller.rb
app/controllers/api/v1/properties_controller.rb
app/models/address.rb
app/models/landlord.rb
app/models/property.rb
config/routes.rb
package.json
yarn.lock

I intend to use the Address model as an abstract association between Landlord and Property.
So Address is a middle term, but I still haven't worked out the associations and their directions. 
Originally I geocoded the concatenated string with help of pandas in a Jupyter Notebook. 
I did not account for capturing municipality. Instead, I manually updated the records.
What I should have done was capture the municipality code from the csv filename. 
There should be a method or a dictionary for capturing and returning the translated value of the filename's municipality code. Check the landlord_data repo. 
- `properties_controller.page_params` changed to reflect what is being validated in `property.rb`.

Model and controller updates

---

app/controllers/api/v1/properties_controller.rb

It's fixed now, and paginating as it should.

I messed up the index on the Properties controller

---

app/controllers/api/v1/properties_controller.rb
app/javascript/Index.jsx
app/javascript/components/Address/Address.tsx
app/javascript/components/Address/Addresses.tsx
app/javascript/components/Address/CreateAddress.tsx
app/javascript/components/GeocoderForm.tsx
app/javascript/components/Landlord/Landlords.tsx
app/javascript/components/NavBar.tsx
app/javascript/components/Property/PropertyForm.tsx
app/javascript/components/Property/useProperty.tsx
node_modules/@types/react-table/index.d.ts
yarn.lock

Address interface updated with optional types. All fields other than the necessary ones should be optional in this way.  
Interface props have been moved around to their proper locations.

React components updating with proper types

---

.yarnclean
Gemfile.lock
app/models/landlord.rb
app/models/property.rb
babel.config.js
package.json
spec/javascript/components/Property/Properties.spec.tsx
yarn.lock

Jest tests now run. Although I don't have any written.

Jest config finished, tests can run now

---

app/javascript/Index.jsx
package.json
yarn.lock

Minimal changes were necessary to make this upgrade. 
Ensured the types and dependencies matched React.

Bumping React 17.0.2 to React 18.1

---

app/models/address.rb
app/models/property.rb
db/migrate/20220520001953_add_property_id_as_foreign_key_on_addresses.rb

I am not sure why `Properties.tsx` stopped loading…
Moved the first conditional check in Property.rb's callback methods to where it should've been all along…

Properties.tsx now loading correctly

---

app/models/property.rb

I forgot to add the id of the new_address within the update method.

Method fix

---

README.md
app/controllers/api/v1/addresses_controller.rb
app/javascript/components/Address/Address.tsx
app/javascript/components/Address/AddressForm.tsx
app/javascript/components/Address/Addresses.tsx
app/javascript/components/Address/useAddressesCount.tsx
app/javascript/components/CountsTable.tsx
app/javascript/components/Home.tsx
app/javascript/components/Landlord/Landlord.tsx
app/javascript/components/Landlord/useLandlordsCount.tsx
app/javascript/components/Property/Properties.tsx
app/javascript/components/Property/Property.tsx
app/javascript/components/Property/usePropertiesCount.tsx
app/javascript/components/SelectField.tsx
package.json
yarn.lock

Address.rb
- added render json template
Address.tsx
- fixed interface attributes
AddressForm.tsx
- using Formik — haven't tried it out yet — doesn't really do anything yet —
use…Counts.tsx
- components now return the count of models via react-query. However the pagination on Property seems to change the behavior.

React component updates

---

spec/models/property_spec.rb

Linter caught redundant fields.

---

app/models/address.rb

To reflect the update foreign_keys.

Address fixes

---

package.json

We're not using babel anymore so we don't this section.

Removing babel section from package.json

---

Gemfile.lock
app/javascript/entrypoints/application.scss
app/views/layouts/application.html.erb
package.json
yarn.lock

A little tweaking of the `application.html.erb` file was necessary. 
- removed the esbuild tags. 
- removed the bootstrap tag. 
- removed the needless esbuild tag in the body. 
It builds as it should.

Vite builds and picks up assets.

---

app/javascript/components/Property/Properties.tsx
app/javascript/components/Property/useProperty.tsx

Not sure what possessed me to adopt this style…maybe the React Router documentation?

Fixing 'id' on Properties component
